rm params_saved.json
rm optimize.nc
rm geology-optimized.nc
rm convergence.png
rm rms_std.dat
rm costs.dat
rm params_saved.json
rm optimize.nc
rm params_saved.json
rm optimize.nc
rm geology-optimized.nc
rm convergence.png
rm rms_std.dat
rm costs.dat
rm params_saved.json
rm optimize.nc
rm geology-optimized.nc
rm convergence.png
rm rms_std.dat
rm costs.dat
rm params_saved.json
rm optimize.nc
rm geology-optimized.nc
rm convergence.png
rm rms_std.dat
rm costs.dat
rm params_saved.json
rm optimize.nc
rm geology-optimized.nc
rm convergence.png
rm rms_std.dat
rm costs.dat
rm params_saved.json
rm optimize.nc
rm geology-optimized.nc
rm convergence.png
rm rms_std.dat
rm costs.dat
rm params_saved.json
rm optimize.nc
rm geology-optimized.nc
rm convergence.png
rm rms_std.dat
rm costs.dat
rm params_saved.json
rm optimize.nc
rm geology-optimized.nc
rm convergence.png
rm rms_std.dat
rm costs.dat
rm params_saved.json
rm optimize.nc
rm geology-optimized.nc
rm convergence.png
rm rms_std.dat
rm costs.dat
rm params_saved.json
rm optimize.nc
rm geology-optimized.nc
rm convergence.png
rm rms_std.dat
rm costs.dat
rm params_saved.json
rm optimize.nc
rm geology-optimized.nc
rm convergence.png
rm rms_std.dat
rm costs.dat
